### ISSUE TITLE
Cannot read property 'widget' of undefined

### ISSUE THREAD

**Issue by michalMajkel** [nstudio/nativescript-checkbox#112]
Hi,

Just installed the plugin ( angular ), added checkbox to one of my html pages and below exception occurs. I am using Nativescript 6.0 R.C. - is this supported ?
```
System.err: TypeError: Cannot read property 'widget' of undefined
System.err:
System.err: StackTrace:
System.err:     Frame: function:'push.../node_modules/nativescript-checkbox/checkbox.js.CheckBox.createNativeView', file:'file:///node_modules\nativescript-checkbox\checkbox.js:152:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:491:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules\tns-core-modules\ui\layouts\layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules\tns-core-modules\ui\layouts\layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView', file:'file:///node_modules\tns-core-modules\ui\content-view\content-view.js:70:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules\tns-core-modules\ui\layouts\layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///node_modules\tns-core-modules\ui\layouts\layout-base-common.js:125:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:533:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView', file:'file:///node_modules\tns-core-modules\ui\content-view\content-view.js:70:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.eachChildView', file:'file:///node_modules\tns-core-modules\ui\page\page-common.js:126:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///node_modules\tns-core-modules\ui\core\view\view-common.js:992:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:532:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addViewCore', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:431:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView', file:'file:///node_modules\tns-core-modules\ui\core\view-base\view-base.js:420:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView', file:'file:///node_modules\tns-core-modules\ui\frame\frame.js:684:0
System.err:     Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView', file:'file:///node_modules\tns-core-modules\ui\frame\fragment.js:26:0
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     at android.os.Handler.handleCallback(Handler.java:883)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7319)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
```

**Comment by bradmartin** [comment]
Be sure you're not using the deprecated package.
