### ISSUE TITLE
Plugin breaks after updating to {N} 6

### ISSUE THREAD

**Issue by hermandinho** [nstudio/nativescript-checkbox#114]
Hello guys and thkans for the great plugin. Every things was working for {N} 5.4. But when i migrated to {N} 6.0, i receive this error during build

`
Exception in thread "main" java.lang.RuntimeException: Class not found android.support.v4.view.ViewPager.OnPageChangeListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
        at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:50)
`

is there a solution for that?

**Comment by 000panther** [comment]
Use: https://www.npmjs.com/package/@nstudio/nativescript-checkbox
